version: '3'

services:
  cron:
    restart: always
    build: .
    env_file: .env
    command: crond -f -l 8
    volumes:
      - ./cron:/etc/periodic/cron/:ro
    depends_on:
      - cache

  cache:
    image: redis:alpine
    restart: always
    env_file: .env
    volumes:
      - ./data/redis:/data
      - ./config/redis.conf:/redis.conf:ro
    command: [ "redis-server", "/redis.conf" ]
